"""Seed data for wildlife species and conservation stories."""

import json

from app.images import PHOTOS, unsplash

SPECIES_DATA = [
    {
        "name": "African Elephant",
        "scientific_name": "Loxodonta africana",
        "habitat": "Grasslands",
        "conservation_status": "Endangered",
        "population_trend": "Decreasing",
        "description": "The largest land mammal on Earth, African elephants are keystone species that shape savanna ecosystems through seed dispersal and creating water access points for other wildlife.",
        "image_url": unsplash(PHOTOS["elephant"]),
        "interesting_fact": "Elephants can communicate using infrasound over distances of up to 10 kilometers.",
    },
    {
        "name": "Bengal Tiger",
        "scientific_name": "Panthera tigris tigris",
        "habitat": "Rainforests",
        "conservation_status": "Endangered",
        "population_trend": "Stable",
        "description": "Apex predators of the Indian subcontinent, Bengal tigers regulate prey populations and maintain the health of forest ecosystems across their range.",
        "image_url": unsplash(PHOTOS["orangutan"]),
        "interesting_fact": "Each tiger's stripe pattern is unique, like a human fingerprint.",
    },
    {
        "name": "Blue Whale",
        "scientific_name": "Balaenoptera musculus",
        "habitat": "Oceans",
        "conservation_status": "Endangered",
        "population_trend": "Increasing",
        "description": "The largest animal ever known to have existed, blue whales play a vital role in ocean nutrient cycling through their feeding and migration patterns.",
        "image_url": unsplash(PHOTOS["ocean"]),
        "interesting_fact": "A blue whale's heart is roughly the size of a small car.",
    },
    {
        "name": "Emperor Penguin",
        "scientific_name": "Aptenodytes forsteri",
        "habitat": "Polar Regions",
        "conservation_status": "Near Threatened",
        "population_trend": "Decreasing",
        "description": "These remarkable birds endure the harshest conditions on Earth, breeding during Antarctic winters in colonies that can number in the thousands.",
        "image_url": unsplash(PHOTOS["mountains_snow"]),
        "interesting_fact": "Male emperor penguins fast for up to 120 days while incubating eggs.",
    },
    {
        "name": "Snow Leopard",
        "scientific_name": "Panthera uncia",
        "habitat": "Mountains",
        "conservation_status": "Vulnerable",
        "population_trend": "Decreasing",
        "description": "Ghost cats of the high Himalayas, snow leopards are indicators of healthy mountain ecosystems spanning twelve countries in Central and South Asia.",
        "image_url": unsplash(PHOTOS["mountains_snow"]),
        "interesting_fact": "Snow leopards can leap up to 15 meters in a single bound.",
    },
    {
        "name": "Giant Panda",
        "scientific_name": "Ailuropoda melanoleuca",
        "habitat": "Mountains",
        "conservation_status": "Vulnerable",
        "population_trend": "Increasing",
        "description": "Once on the brink of extinction, giant pandas have become a global symbol of conservation success through decades of dedicated protection efforts.",
        "image_url": unsplash(PHOTOS["panda"]),
        "interesting_fact": "Pandas spend up to 14 hours a day eating bamboo.",
    },
    {
        "name": "Green Sea Turtle",
        "scientific_name": "Chelonia mydas",
        "habitat": "Oceans",
        "conservation_status": "Endangered",
        "population_trend": "Decreasing",
        "description": "Ancient mariners of the sea, green turtles maintain seagrass beds and coral reef health through their grazing behavior across tropical oceans.",
        "image_url": unsplash(PHOTOS["sea_turtle"]),
        "interesting_fact": "Green turtles can navigate thousands of miles to return to their birthplace to nest.",
    },
    {
        "name": "Orangutan",
        "scientific_name": "Pongo pygmaeus",
        "habitat": "Rainforests",
        "conservation_status": "Critically Endangered",
        "population_trend": "Decreasing",
        "description": "Highly intelligent great apes of Borneo and Sumatra, orangutans are essential seed dispersers in tropical rainforest ecosystems.",
        "image_url": unsplash(PHOTOS["orangutan"]),
        "interesting_fact": "Orangutans share approximately 97% of their DNA with humans.",
    },
    {
        "name": "Polar Bear",
        "scientific_name": "Ursus maritimus",
        "habitat": "Polar Regions",
        "conservation_status": "Vulnerable",
        "population_trend": "Decreasing",
        "description": "Marine mammals of the Arctic, polar bears depend on sea ice for hunting and are among the most visible indicators of climate change impacts.",
        "image_url": unsplash(PHOTOS["mountains_snow"]),
        "interesting_fact": "Polar bear fur is transparent, not white — it reflects visible light.",
    },
    {
        "name": "Amur Leopard",
        "scientific_name": "Panthera pardus orientalis",
        "habitat": "Forests",
        "conservation_status": "Critically Endangered",
        "population_trend": "Increasing",
        "description": "One of the rarest big cats on Earth, the Amur leopard survives in the temperate forests of the Russian Far East and northeastern China.",
        "image_url": unsplash(PHOTOS["leopard"]),
        "interesting_fact": "Fewer than 100 Amur leopards remain in the wild.",
    },
    {
        "name": "Saiga Antelope",
        "scientific_name": "Saiga tatarica",
        "habitat": "Grasslands",
        "conservation_status": "Critically Endangered",
        "population_trend": "Increasing",
        "description": "Ancient nomads of the Eurasian steppe, saiga antelopes undertake one of the most spectacular migrations on the planet each year.",
        "image_url": unsplash(PHOTOS["grasslands"]),
        "interesting_fact": "Saiga antelopes have distinctive bulbous noses that filter dust and warm cold air.",
    },
    {
        "name": "Fennec Fox",
        "scientific_name": "Vulpes zerda",
        "habitat": "Deserts",
        "conservation_status": "Least Concern",
        "population_trend": "Stable",
        "description": "The smallest fox species, fennec foxes are perfectly adapted to desert life with oversized ears that dissipate heat and detect prey underground.",
        "image_url": unsplash(PHOTOS["fox"]),
        "interesting_fact": "Fennec fox ears can grow up to 15 centimeters long.",
    },
    {
        "name": "Humpback Whale",
        "scientific_name": "Megaptera novaeangliae",
        "habitat": "Oceans",
        "conservation_status": "Least Concern",
        "population_trend": "Increasing",
        "description": "Known for their spectacular breaching and complex songs, humpback whales migrate up to 16,000 kilometers annually between feeding and breeding grounds.",
        "image_url": unsplash(PHOTOS["ocean"]),
        "interesting_fact": "Humpback whale songs can last up to 20 minutes and evolve each season.",
    },
    {
        "name": "Mountain Gorilla",
        "scientific_name": "Gorilla beringei beringei",
        "habitat": "Mountains",
        "conservation_status": "Endangered",
        "population_trend": "Increasing",
        "description": "Living in the cloud forests of the Virunga Mountains, mountain gorillas represent one of conservation's greatest recovery stories.",
        "image_url": unsplash(PHOTOS["gorilla"]),
        "interesting_fact": "Mountain gorilla groups are led by a dominant silverback male.",
    },
    {
        "name": "Jaguar",
        "scientific_name": "Panthera onca",
        "habitat": "Rainforests",
        "conservation_status": "Near Threatened",
        "population_trend": "Decreasing",
        "description": "The apex predator of the Americas, jaguars maintain balance in tropical ecosystems from the Amazon to the southwestern United States.",
        "image_url": unsplash(PHOTOS["leopard"]),
        "interesting_fact": "Jaguars have the strongest bite of any big cat relative to body size.",
    },
    {
        "name": "Arctic Fox",
        "scientific_name": "Vulpes lagopus",
        "habitat": "Polar Regions",
        "conservation_status": "Least Concern",
        "population_trend": "Stable",
        "description": "Masters of Arctic survival, Arctic foxes change coat color with the seasons and can endure temperatures as low as -50°C.",
        "image_url": unsplash(PHOTOS["fox"]),
        "interesting_fact": "Arctic foxes have fur on the soles of their feet for insulation.",
    },
    {
        "name": "Black Rhinoceros",
        "scientific_name": "Diceros bicornis",
        "habitat": "Grasslands",
        "conservation_status": "Critically Endangered",
        "population_trend": "Increasing",
        "description": "Despite facing severe poaching pressure, black rhino populations are slowly recovering thanks to intensive anti-poaching and habitat protection programs.",
        "image_url": unsplash(PHOTOS["elephant"]),
        "interesting_fact": "Black rhinos can run at speeds up to 55 km/h despite weighing over a ton.",
    },
    {
        "name": "Red Panda",
        "scientific_name": "Ailurus fulgens",
        "habitat": "Mountains",
        "conservation_status": "Endangered",
        "population_trend": "Decreasing",
        "description": "Living in the bamboo forests of the Eastern Himalayas, red pandas are the only living members of their taxonomic family.",
        "image_url": unsplash(PHOTOS["red_panda"]),
        "interesting_fact": "Red pandas use their bushy tails as blankets during cold mountain nights.",
    },
    {
        "name": "Whale Shark",
        "scientific_name": "Rhincodon typus",
        "habitat": "Oceans",
        "conservation_status": "Endangered",
        "population_trend": "Decreasing",
        "description": "The gentle giants of the ocean, whale sharks are filter feeders that migrate vast distances following plankton blooms.",
        "image_url": unsplash(PHOTOS["sea_turtle"]),
        "interesting_fact": "Whale sharks have unique spot patterns used to identify individuals.",
    },
    {
        "name": "Cheetah",
        "scientific_name": "Acinonyx jubatus",
        "habitat": "Grasslands",
        "conservation_status": "Vulnerable",
        "population_trend": "Decreasing",
        "description": "The fastest land animal, capable of reaching 112 km/h in short bursts, cheetahs are specialized predators of African and Iranian grasslands.",
        "image_url": unsplash(PHOTOS["leopard"]),
        "interesting_fact": "Cheetahs can accelerate from 0 to 96 km/h in just 3 seconds.",
    },
]

STORIES_DATA = [
    {
        "title": "Bringing Back the Bald Eagle",
        "summary": "Once on the brink of extinction in the continental United States, the bald eagle has made a remarkable recovery through banning DDT and dedicated conservation efforts.",
        "image_url": unsplash(PHOTOS["birds"]),
        "achievements": [
            "Removed from the Endangered Species List in 2007",
            "Population grew from 417 nesting pairs in 1963 to over 71,000 today",
            "Protected under multiple federal laws",
            "Habitat restoration across nesting territories",
        ],
        "timeline": [
            {"year": "1963", "event": "Only 417 nesting pairs remain in the lower 48 states"},
            {"year": "1972", "event": "DDT banned in the United States"},
            {"year": "1978", "event": "Bald eagle listed as endangered nationwide"},
            {"year": "1995", "event": "Status upgraded to threatened"},
            {"year": "2007", "event": "Removed from Endangered Species List"},
        ],
    },
    {
        "title": "Giant Panda Recovery",
        "summary": "The giant panda's journey from endangered to vulnerable status represents decades of international cooperation and habitat protection in China.",
        "image_url": unsplash(PHOTOS["panda"]),
        "achievements": [
            "Wild population increased to over 1,800 individuals",
            "67 protected panda reserves established",
            "IUCN status improved from Endangered to Vulnerable",
            "Bamboo corridor networks connecting fragmented habitats",
        ],
        "timeline": [
            {"year": "1980", "event": "First panda reserves established in Sichuan"},
            {"year": "1990", "event": "International panda conservation partnerships begin"},
            {"year": "2003", "event": "Wild population census shows 1,596 pandas"},
            {"year": "2016", "event": "IUCN downlists pandas from Endangered to Vulnerable"},
            {"year": "2021", "event": "Giant Panda National Park officially established"},
        ],
    },
    {
        "title": "Mountain Gorilla Renaissance",
        "summary": "Through relentless anti-poaching patrols and community engagement, mountain gorilla populations have grown steadily in the Virunga Mountains.",
        "image_url": unsplash(PHOTOS["gorilla"]),
        "achievements": [
            "Population grew from 620 in 1989 to over 1,000 today",
            "Ecotourism provides sustainable income for local communities",
            "Cross-border cooperation between Rwanda, Uganda, and DRC",
            "Veterinary programs treat injured and sick gorillas",
        ],
        "timeline": [
            {"year": "1981", "event": "Dian Fossey's research brings global attention"},
            {"year": "1991", "event": "International Gorilla Conservation Programme launched"},
            {"year": "2008", "event": "Population census confirms growth to 780 individuals"},
            {"year": "2018", "event": "IUCN downlists from Critically Endangered to Endangered"},
            {"year": "2023", "event": "Population exceeds 1,000 for the first time"},
        ],
    },
    {
        "title": "Humpback Whale Comeback",
        "summary": "After commercial whaling decimated populations, humpback whales have recovered across most of their range thanks to international protection agreements.",
        "image_url": unsplash(PHOTOS["ocean"]),
        "achievements": [
            "Global population estimated at 135,000 individuals",
            "Removed from endangered lists in multiple regions",
            "International whaling moratorium upheld since 1986",
            "Marine protected areas expanded along migration routes",
        ],
        "timeline": [
            {"year": "1966", "event": "Commercial whaling reduces populations by 90%"},
            {"year": "1986", "event": "International Whaling Commission moratorium enacted"},
            {"year": "1990", "event": "First signs of population recovery observed"},
            {"year": "2016", "event": "Most populations removed from endangered lists"},
            {"year": "2022", "event": "Global humpback population reaches pre-whaling estimates"},
        ],
    },
    {
        "title": "Rewilding the European Bison",
        "summary": "Europe's largest land mammal was hunted to extinction in the wild, but reintroduction programs have restored free-roaming bison across the continent.",
        "image_url": unsplash(PHOTOS["bison"]),
        "achievements": [
            "Over 9,000 bison now live in free-ranging herds",
            "Reintroduced to Poland, Romania, and Germany",
            "Keystone species restoring grassland ecosystems",
            "First wild births recorded in Netherlands in 500 years",
        ],
        "timeline": [
            {"year": "1927", "event": "Last wild European bison killed in Caucasus"},
            {"year": "1952", "event": "First reintroduction in Białowieża Forest, Poland"},
            {"year": "2014", "event": "Bison reintroduced to Romania's Carpathian Mountains"},
            {"year": "2016", "event": "First wild bison born in Netherlands since Middle Ages"},
            {"year": "2023", "event": "European bison population exceeds 9,000"},
        ],
    },
    {
        "title": "Saving the California Condor",
        "summary": "From just 27 individuals in 1987, intensive captive breeding and release programs have brought the California condor back from the edge of extinction.",
        "image_url": unsplash(PHOTOS["birds"]),
        "achievements": [
            "Population recovered from 27 to over 560 birds",
            "Successful breeding in both captivity and the wild",
            "Lead ammunition bans protect condors from poisoning",
            "Monitoring programs track every released individual",
        ],
        "timeline": [
            {"year": "1982", "event": "Only 22 California condors remain in the wild"},
            {"year": "1987", "event": "Last wild condor captured for captive breeding"},
            {"year": "1992", "event": "First condors released back into the wild"},
            {"year": "2008", "event": "Wild population exceeds 100 individuals"},
            {"year": "2024", "event": "Total population surpasses 560 condors"},
        ],
    },
]


def serialize_story(story_dict: dict) -> dict:
    """Convert list fields to JSON strings for database storage."""
    return {
        **story_dict,
        "achievements": json.dumps(story_dict["achievements"]),
        "timeline": json.dumps(story_dict["timeline"]),
    }
